/**
 * @file 12.c
 *
 * @brief Highly divisible triangular number
 *
 * The sequence of triangle numbers is generated by adding the natural numbers. So
 * the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
 *
 * The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *   1: 1
 *   3: 1,3
 *   6: 1,2,3,6
 *   10: 1,2,5,10
 *   15: 1,3,5,15
 *   21: 1,3,7,21
 *   28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 */

#include "stdbool.h"
#include "stdint.h"

#include <stdio.h>
#include <stdlib.h>

uint16_t count_divisors(uint64_t value) {
  uint64_t halfway = (value / 2) + 1;
  uint16_t count = 2;
  for(uint64_t i = 2; i <= halfway; i++) {
    if(value % i == 0) count++;
  }
  return count;
}

int main(int argc, char *argv[]) {
  uint16_t threshold = atoi(argv[1]);

  uint64_t value = 0;
  uint64_t i = 1;
  while(true) {
    value += i;

    if(threshold < count_divisors(value)) {
      printf("First triangle above %i: %lu\n", threshold, value);
      return 0;
    }

    i++;
  }

  printf("Failure... :(\n");
  return 1;
}
