/**
 * @file 2.c
 *
 * @brief Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include "stdbool.h"
#include "stdint.h"
#include "stdlib.h"

#include <stdio.h>

typedef struct Buffer {
  uint64_t values[2];
  uint8_t index;
} Buffer;

/**
 * @return New buffer
 */
Buffer buffer_new(void) {
  Buffer buffer = {
    .values = {0, 1},
    .index = 1
  };
  return buffer;
}

/**
 * @param buffer Buffer to advance
 * @return Next value
 */
uint64_t next_fibonacci_value(Buffer *buffer) {
  uint64_t next = buffer->values[0] + buffer->values[1];
  buffer->index = buffer->index == 0 ? 1 : 0;
  buffer->values[buffer->index] = next;
  return next;
}

uint8_t main(uint8_t argc, uint8_t *argv[]) {
  uint64_t max_value = atoi(argv[1]);

  Buffer buffer = buffer_new();
  uint64_t total = 0;
  uint64_t current = 0;
  while(true) {
    current = next_fibonacci_value(&buffer);

    if(max_value < current)
      break;

    if(!(current & 1)) {
      total += current;
    }
  }

  printf("Total: %lu\n", total);

  return 0;
}
